### ISSUE TITLE
Review bpo-36795: "make venv" failed in Docs

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#46] opened 2022-04-05 23:30 UTC
[An open issue](https://bugs.python.org/issue36795) that you may be able to resolve.

**Comment by hugovk** [comment] 2022-04-06 08:25
Thanks, I've closed it as neither xtream or I can reproduce it (without hacking pip) and it's likely caused by using a very old version of pip (9.0.1 from Nov 6, 2016).

Let's close this issue too.

**Closed** 2022-04-06 17:31 UTC
